### PR TITLE
Integration test for lib/util/

### LINKED ISSUE #143: Create integration tests for modules in lib/util
Order of completion:    
 - [x] json_encoder.py 
 - [x] graph.py
 - [x] preprocess.py
 - [x] union_find.py
 - [ ] layout.py

### PR DESCRIPTION
**Pull request by hrishikesh-dahiya**
## Description
 - This PR focuses on integration testing of python scripts in lib/util/
 - Fixes #143 
 - Order of testing: 1. json_enoder.py

## Motivation
 - To increase the code coverage
 
 ## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checks
 - [ ] Squash your commits down to one, or a few, discreet changesets before submitting a pull request
 - [x] Read the [contributing guide](https://github.com/DeveloperCAP/MLCAT/blob/development/.github/CONTRIBUTING.md)
 - [x] PR should be motivated, i.e. what does it fix, why, and if relevant how
 - [x] If possible, include an example in the description, that could help all readers (including project members) to get a better picture of the change
 - [ ] Avoid other runtime dependencies unless absolutely necessary 
 - [ ] Rebase your commit history so that each commit is meaningful and states the intention behind the change 
 - [x] Ensure that your pull request follows the [style guidelines](https://github.com/DeveloperCAP/MLCAT/wiki/Coding-Guidelines)
 - [x] At least one commit should mention `Fixes #143` _if relevant_

## Notify reviewers
@prasadtalasila

### CODE REVIEW

**Comment by hrishikesh-dahiya** [comment]
Work in Progress. DO NOT MERGE.

**Comment by hrishikesh-dahiya** [comment]
The integration test structure is in place, the modules are changed with correct import files, `json_encoder.py` has now 100% codecov. What should be done for `lib/test_integration.py` ? Move it to test/ directory as it is or break down into smaller tests for individual scripts?


ref. https://codecov.io/gh/DeveloperCAP/MLCAT/pull/145/tree/lib/util for codecov of json_encoder.py

**Comment by prasadtalasila** [comment]
@hrishikesh-dahiya please move the test_integration.py from lib/ to test directory. Leave the file as is for now.

**Comment by hrishikesh-dahiya** [comment]
removed `test_integration.py` as per the discussion on slack

**Pull request merged**
