### PR TITLE
Update README.md

### LINKED ISSUE #125: Update README.md
Update the readme along the lines of [README.md](https://github.com/AutolabJS/AutolabJS/blob/master/README.md) for AutolabJS project.

We need to create wiki pages for **Install and Use**, **Features**. Add hyperlinks to all the files created in issue #124.

**Install and Use** page has to be created with reference to PR #120.

### PR DESCRIPTION
**Pull request by naveen-hr**
## Description
 - Removed Usage, Documentation, Testing framework,Installation and License. 
 - Added links to Documentation and Wiki
 - Wiki pages need to be created for Install and Use, Features and Writing Documentation.
 - Fix #125 

## Motivation
 - To concise the README 

 ## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checks
 - [x] Squash your commits down to one, or a few, discreet changesets before submitting a pull request
 - [x] Read the [contributing guide](https://github.com/DeveloperCAP/MLCAT/blob/development/.github/CONTRIBUTING.md)
 - [x] PR should be motivated, i.e. what does it fix, why, and if relevant how
 - [ ] If possible, include an example in the description, that could help all readers (including project members) to get a better picture of the change
 - [x] Avoid other runtime dependencies unless abslutely necessary 
 - [x] Rebase your commit history so that each commit is meaningful and states the intention behind the change 
 - [x] Ensure that your pull request follows the [style guidelines](https://github.com/DeveloperCAP/MLCAT/wiki/Coding-Guidelines)
 - [x] At least one commit should mention `Fixes #125` 

## Notify reviewers
@prasadtalasila

### CODE REVIEW

**Comment by naveen-hr** [comment]
CodeClimate Maintainability badge is broken, please provide the link

**Comment by prasadtalasila** [comment]
@naveen-hr Here are a few corrections:

1. The codequality badge from codeclimate is not showing. Please update the badge to the following code.
    ```
    [![Maintainability](https://api.codeclimate.com/v1/badges/74ec741f24466f33f083/maintainability)](https://codeclimate.com/github/DeveloperCAP/MLCAT/maintainability)
    ```

1. Link to features page: https://github.com/prasadtalasila/MailingListParser/wiki/Features
1. Link to install and use page: https://github.com/DeveloperCAP/MLCAT/wiki/Install-and-Use

Please update the wiki pages with relevant information.

**Comment by naveen-hr** [comment]
The corrections have been done.

**Comment by prasadtalasila** [comment]
@naveen-hr Please update the [features](https://github.com/DeveloperCAP/MLCAT/wiki/Features) page. It is better to read through the documentation and summarise the features available in the software. You can cross-verify the summary with the help of @yashpungaliya.

**Comment by prasadtalasila** [comment]
work completed in 0c87597

**Pull request closed without merging**
