### PR TITLE
Main driver to run other drivers

### PR DESCRIPTION
**Pull request by AakankshaSanctis**
Main_driver to run all the drivers one after another

### CODE REVIEW

**Comment by achyudh** [comment]
This is not a clean way to do it, and I recommend a shell script. Your are modifying the PYTHONPATH just to run the driver in this line:

+sys.path.append(os.path.join(os.path.dirname(__file__), "lib"))

This is not the best way to do it even though this is only a temporary change to the PYTHONPATH .

**Comment by hrishikesh-dahiya** [comment]
I think in the shell script also we would have to change the PYHTONPATH. Otherwise, it is not running it.

**Comment by AakankshaSanctis** [comment]
Yeah because everytime we run the drivers we have to define the PYTHONPATH

**Comment by achyudh** [comment]
Can you please post the error? I usually just run the driver file from within Pycharm. I guess Pycharm predefines the PYTHONPATH for me.

**Comment by achyudh** [comment]
Otherwise, this change looks good. I had just that one problem.

**Comment by hrishikesh-dahiya** [comment]
Without this change, it is not able to find the lib module

**Comment by prasadtalasila** [comment]
Thanks everyone. Its a good PR with lots of discussion.

**Pull request merged**
