### PR TITLE
Integration test

### PR DESCRIPTION
**Pull request by naveen-hr**
## Description
 - Integration test for read.py

## Motivation
 - Why is this change required? What problem does it solve?
 - If it fixes an open issue, please link to the issue here, and in the commit message. 
 
 ## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Notify reviewers
@prasadtalasila

### CODE REVIEW

**Comment by prasadtalasila** [comment]
@naveen-hr There are merge conflicts. You need to rebase your branch.

**Comment by prasadtalasila** [comment]
@hrishikesh-dahiya are you working on this?

**Comment by hrishikesh-dahiya** [comment]
Yes sir, I will complete the pending work by Tuesday.

**Comment by hrishikesh-dahiya** [comment]
#178 solves this

**Pull request closed without merging**
