### PR TITLE
Install script

### LINKED ISSUE #119: check install setup using virtualenv
The existing installation setup installs everything directly onto the base OS. Let's check the process with virtualenv and see if it goes through smoothly.

@tejalwakchoure can work on this as a first issue.

### PR DESCRIPTION
**Pull request by prasadtalasila**
## What? Why?
Fix #119 .
Improves PR #134 

Changes proposed in this pull request:
- Improves the installation script and removes errors.
- Makes the installation atomic operation, i.e., repeated installations do not have any undesirable effect.

## Checks
- [ ] Single commit and [No merge commits](http://nathanleclaire.com/blog/2014/09/14/dont-be-scared-of-git-rebase/)
- [ ] Make sure you have added required documentation
- [x] If you have refactored a code, make sure that you have compared the outputs pre and post refactoring. Add both pre and post refaoring screenshots below if the output is visual

## Notify reviewers
@tejalwakchoure @AakankshaSanctis

### CODE REVIEW

**Comment by prasadtalasila** [comment]
The Infomaps installation section needs to be protected with a check against an existing installation of Infomap. Otherwise, rest seems set for an atomic installation.

**Comment by prasadtalasila** [comment]
The work on atomic installation of Infomap is complete. 

@tejalwakchoure and @AakankshaSanctis please review the code to check for mistakes. If everything is okay, we can go ahead with the merge of the PR.

**Comment by AakankshaSanctis** [comment]
The code looks fine,I think we can go ahead and merge it

**Comment by tejalwakchoure** [comment]
yes, it is working correctly.

**Pull request merged**
